In [ ]:
from google.colab import drive
import pandas as pd
import igraph as ig
import numpy as np
import random

drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Fragment/fragmentTry/df_step5.csv')
edges_df = pd.read_csv('/content/drive/MyDrive/Fragment/fragmentTry/graph_step5.edgelist', sep=' ', names=['source', 'target', 'weight'])
g = ig.Graph.TupleList(edges_df.itertuples(index=False), weights=True)
node_names = g.vs['name']

print(f"{g.vcount()} nodes, {g.ecount()} edges")

Requirement already satisfied: python-igraph in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: igraph==1.0.0 in /usr/local/lib/python3.12/dist-packages (from python-igraph) (1.0.0)
Requirement already satisfied: texttable>=1.6.2 in /usr/local/lib/python3.12/dist-packages (from igraph==1.0.0->python-igraph) (1.7.0)
Note: to be able to use all crisp methods, you need to install some additional packages:  {'graph_tool', 'infomap', 'leidenalg', 'bayanpy'}
Note: to be able to use all crisp methods, you need to install some additional packages:  {'pyclustering', 'ASLPAw'}
Note: to be able to use all crisp methods, you need to install some additional packages:  {'infomap', 'leidenalg'}
Mounted at /content/drive
igraph: 102649 nodes, 30609071 edges

# Leiden

In [ ]:
random.seed(42)
np.random.seed(42)

partition = g.community_leiden(weights='weight', objective_function='modularity')

print(f"number of social communities: {len(partition)}")
print(f"modularity score: {g.modularity(partition.membership, weights='weight'):.4f}")

#add results to df
results = {node['name']: partition.membership[i] for i, node in enumerate(g.vs)} #key = asset name, value = community id
df['comm_louvain'] = df['Asset'].map(results)

Tempo: 46.1s
Leiden:
Number of communities: 138
Modularity score: 0.7468

In [ ]:
from collections import Counter

leiden_counts = Counter(part_leiden.membership)
leiden_sizes = pd.DataFrame(leiden_counts.most_common(), columns=['community_id', 'size'])
print(leiden_sizes.head(20))

    community_id   size
0              0  10104
1              6   9706
2             12   9105
3             10   6988
4             21   6517
5              4   5210
6             22   4216
7              1   3742
8              2   3422
9             55   3388
10             3   3040
11             8   2959
12            16   2820
13            18   2366
14            57   1905
15             5   1881
16            54   1764
17            43   1669
18            60   1538
19            27   1215

In [ ]:
df

,Asset,Scrape date,Ownership history,Bids,Resale,Highest bid,grado_asset,length,n_alpha,n_digit,...,emb_1018,emb_1019,emb_1020,emb_1021,emb_1022,emb_1023,linguistic_cluster,comm_angel_all,comm_angel,comm_leiden
0,@dubaihouse,2025-09-30 02:34:42,"[{'Owner': 'conig.t.me', 'Date of Sale': '2024...",[],NaN,NaN,1.0,10,10,0,...,-0.039585,-0.025285,0.020210,0.002030,-0.039038,-0.021936,16,[0],0.0,25
1,@totln,2025-11-16 20:42:28,[{'Owner': 'UQBB5t1vKAJMgLj-5cGHXhxqweHSxNkm0z...,[],NaN,NaN,1.0,5,5,0,...,-0.008787,0.011834,-0.014221,-0.033157,-0.023512,-0.025341,0,[15],15.0,61
2,@hangzhoubot,2025-11-13 06:50:16,"[{'Owner': 'mahua.t.me', 'Date of Sale': '2025...",[],NaN,NaN,4.0,11,11,0,...,-0.025089,-0.044691,-0.005340,0.034371,-0.033242,0.027659,3,[1],1.0,55
3,@gssssss,2025-11-13 06:34:48,[{'Owner': 'UQAVWbDUur7WDLwT71dzKf5RDZfTUHTnWE...,[],NaN,NaN,2.0,7,7,0,...,-0.052073,0.012337,0.012308,0.022585,-0.009809,-0.003181,17,[48],48.0,6
4,@kefu586,2025-11-13 09:12:22,[{'Owner': 'UQBC6_I2vvLCUfwNnfSGlrVTmWG7PO1j37...,[],NaN,NaN,1.0,7,4,3,...,-0.046182,-0.024785,0.044084,-0.010170,-0.023104,0.078489,-1,[41],41.0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102644,@toeiloilo,2025-11-16 20:07:25,[{'Owner': 'UQC3cnouK2zl0IYDZXoFLTGPOsfr9byl-G...,[],NaN,NaN,2.0,9,9,0,...,-0.029183,0.036382,-0.016910,-0.025597,-0.005268,0.012683,17,[27],27.0,65
102645,@lvjing,2025-11-14 11:52:34,"[{'Owner': 'tiezi.t.me', 'Date of Sale': '2023...",[],NaN,NaN,3.0,6,6,0,...,-0.037203,-0.031983,0.018343,-0.004952,0.005525,0.032474,2,[35],35.0,21
102646,@milklover,2025-11-14 13:10:00,"[{'Owner': 'sara88.t.me', 'Date of Sale': '202...",[],NaN,NaN,8.0,9,9,0,...,0.016981,0.016153,-0.013385,0.038522,-0.012018,0.055867,15,"[0, 41]",0.0,22
102647,@daili888,2025-11-13 03:01:33,"[{'Owner': 'tantan.t.me', 'Date of Sale': '202...",[],NaN,NaN,1.0,8,5,3,...,-0.018764,0.006023,0.063633,0.007415,0.018738,0.053327,18,[20],20.0,58
102648,@kamylinhbot,2025-11-13 09:04:17,[{'Owner': 'UQCXEDYg5g98vkiyA-l6fWEupiauPRyQsf...,[],NaN,NaN,2.0,11,11,0,...,-0.030082,-0.003107,-0.016577,-0.017852,-0.035809,0.016749,-1,[0],0.0,73

#Louvain

In [ ]:
partition = g.community_multilevel(weights='weight')
print(f"number of social communities: {len(partition)}")
print(f"modularity score: {g.modularity(partition.membership, weights='weight')}")

#add results to df
results = {node['name']: partition.membership[i] for i, node in enumerate(g.vs)} #key = asset name, value = community id
df['comm_louvain'] = df['Asset'].map(results)

number of social communities: 113
modularity score: 0.7445579738735268

In [ ]:
df

,Asset,Scrape date,Ownership history,Bids,Resale,Highest bid,grado_asset,length,n_alpha,n_digit,...,emb_1019,emb_1020,emb_1021,emb_1022,emb_1023,linguistic_cluster,comm_angel_all,comm_angel,comm_leiden,comm_louvain
0,@dubaihouse,2025-09-30 02:34:42,"[{'Owner': 'conig.t.me', 'Date of Sale': '2024...",[],NaN,NaN,1.0,10,10,0,...,-0.025285,0.020210,0.002030,-0.039038,-0.021936,16,[0],0.0,25,24
1,@totln,2025-11-16 20:42:28,[{'Owner': 'UQBB5t1vKAJMgLj-5cGHXhxqweHSxNkm0z...,[],NaN,NaN,1.0,5,5,0,...,0.011834,-0.014221,-0.033157,-0.023512,-0.025341,0,[15],15.0,61,28
2,@hangzhoubot,2025-11-13 06:50:16,"[{'Owner': 'mahua.t.me', 'Date of Sale': '2025...",[],NaN,NaN,4.0,11,11,0,...,-0.044691,-0.005340,0.034371,-0.033242,0.027659,3,[1],1.0,55,13
3,@gssssss,2025-11-13 06:34:48,[{'Owner': 'UQAVWbDUur7WDLwT71dzKf5RDZfTUHTnWE...,[],NaN,NaN,2.0,7,7,0,...,0.012337,0.012308,0.022585,-0.009809,-0.003181,17,[48],48.0,6,15
4,@kefu586,2025-11-13 09:12:22,[{'Owner': 'UQBC6_I2vvLCUfwNnfSGlrVTmWG7PO1j37...,[],NaN,NaN,1.0,7,4,3,...,-0.024785,0.044084,-0.010170,-0.023104,0.078489,-1,[41],41.0,13,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102644,@toeiloilo,2025-11-16 20:07:25,[{'Owner': 'UQC3cnouK2zl0IYDZXoFLTGPOsfr9byl-G...,[],NaN,NaN,2.0,9,9,0,...,0.036382,-0.016910,-0.025597,-0.005268,0.012683,17,[27],27.0,65,33
102645,@lvjing,2025-11-14 11:52:34,"[{'Owner': 'tiezi.t.me', 'Date of Sale': '2023...",[],NaN,NaN,3.0,6,6,0,...,-0.031983,0.018343,-0.004952,0.005525,0.032474,2,[35],35.0,21,21
102646,@milklover,2025-11-14 13:10:00,"[{'Owner': 'sara88.t.me', 'Date of Sale': '202...",[],NaN,NaN,8.0,9,9,0,...,0.016153,-0.013385,0.038522,-0.012018,0.055867,15,"[0, 41]",0.0,22,6
102647,@daili888,2025-11-13 03:01:33,"[{'Owner': 'tantan.t.me', 'Date of Sale': '202...",[],NaN,NaN,1.0,8,5,3,...,0.006023,0.063633,0.007415,0.018738,0.053327,18,[20],20.0,58,27
102648,@kamylinhbot,2025-11-13 09:04:17,[{'Owner': 'UQCXEDYg5g98vkiyA-l6fWEupiauPRyQsf...,[],NaN,NaN,2.0,11,11,0,...,-0.003107,-0.016577,-0.017852,-0.035809,0.016749,-1,[0],0.0,73,38

In [ ]:
df.to_csv('/content/drive/MyDrive/df_step6_complete.csv', index=False)